/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 map.glb
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {RigidBody} from "@react-three/rapier";

const MapModel = () => {
    const map = useGLTF("/models/map.glb");

    useEffect(() => {
        map.scene.traverse((child) => {
            if (child.isMesh) {
                child.castShadow = true;
                child.receiveShadow = true;
            }
        })
    }, []);

    return (
            <primitive object={map.scene}/>

    )
}

useGLTF.preload('/models/map.glb')

export default MapModel;
